name: KDT CI
 
on:
 
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup KDT
        run: |
          curl -sSL https://cli.kondukto.io | sh

      - name: Run a SAST scan
        run: |
          kdt list scanners --host https://ourfuturehealth.kondukto.io --token {{secrets.GH_TOKEN}}
